name: Rust

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      run: |
        rustup update stable
        rustup default stable
        rustup target add aarch64-apple-darwin

    - name: Build for x86_64
      run: cargo build --release

    - name: Build for Apple M1
      run: cargo build --release --target=aarch64-apple-darwin

    - name: Archive build artifacts for x86_64
      uses: actions/upload-artifact@v3
      with: 
        name: x86_64-artifact
        path: target/release
    
    - name: Archive build artifacts for Apple M1
      uses: actions/upload-artifact@v3
      with: 
        name: m1-artifact
        path: target/aarch64-apple-darwin/release
    
  release:
    needs: build
    runs-on: macos-latest

    steps:
    - name: Download x86_64 artifacts
      uses: actions/download-artifact@v3
      with:
        name: x86_64-artifact
    
    - name: Download Apple M1 artifacts
      uses: actions/download-artifact@v3
      with:
        name: m1-artifact

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_CDC_GA }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: List files
      run: ls -R
    
    - name: Upload x86_64 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_CDC_GA }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./x86_64-artifact/camdict_cli
        asset_name: fcd_x86_64
        asset_content_type: application/octet-stream

    - name: Upload Apple M1 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_CDC_GA }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./m1-artifact/camdict_cli
        asset_name: fcd_M1
        asset_content_type: application/octet-stream