name: Rust

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      run: |
        rustup update stable
        rustup default stable
        rustup target add aarch64-apple-darwin

    - name: Build for x86_64
      run: cargo build --release

    - name: Build for Apple M1
      run: cargo build --release --target=aarch64-apple-darwin

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_CDC_GA }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload x86_64 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_CDC_GA }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/fcd
        asset_name: fcd_x86_64
        asset_content_type: application/octet-stream

    - name: Upload Apple M1 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_CDC_GA }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/aarch64-apple-darwin/release/fcd
        asset_name: fcd_M1
        asset_content_type: application/octet-stream